"""
Pydantic schemas for Compust Interview Prep Knowledge Center.
Supports multilingual behavioral preparation and repository-backed technical interview tracks.
"""

from typing import Any, List, Optional
from pydantic import BaseModel, Field


class STARStep(BaseModel):
    step: str  # Situation, Task, Action, Result
    definition: str
    key_points: List[str]
    example: str


class STARGuide(BaseModel):
    title: str
    what_is_star: str
    when_to_use: str
    how_to_structure: str
    what_makes_answer_strong: List[str]
    common_mistakes: List[str]
    steps: List[STARStep]


class BehavioralQuestionItem(BaseModel):
    id: str
    category: str
    question: str
    intent: str
    recommended_structure: List[str]
    strong_example_answer: str
    common_pitfalls: List[str]
    self_reflection_prompt: str


class BehavioralPrepResponse(BaseModel):
    language: str
    star_guide: STARGuide
    questions: List[BehavioralQuestionItem]
    story_matrix: Optional[dict] = None
    interview_modules: Optional[List[dict]] = None


class InterviewQuestionSummary(BaseModel):
    id: str
    slug: str
    title: str
    category: str
    topic: str
    difficulty: str  # Fundamental, Intermediate, Advanced
    experience_level: Optional[str] = "Mid-Level"  # Entry-Level / Intern, Mid-Level, Senior / Architect
    target_roles: List[str] = Field(default_factory=list)
    estimated_read_time_min: int
    has_code: bool
    has_diagram: bool


class InterviewTopic(BaseModel):
    id: str
    title: str
    description: Optional[str] = None
    questions: List[InterviewQuestionSummary]


class InterviewCategory(BaseModel):
    id: str
    title: str
    description: Optional[str] = None
    topics: List[InterviewTopic]


class InterviewDomainSummary(BaseModel):
    id: str  # data_engineering, security_engineering, ai_tech_interview
    title: str
    short_title: str
    tagline: str
    description: str
    hero_illustration: str
    total_categories: int
    total_questions: int
    source_repository: str
    source_license: str
    source_url: str


class InterviewDomainTree(BaseModel):
    domain: InterviewDomainSummary
    categories: List[InterviewCategory]


class SourceAttribution(BaseModel):
    repository_name: str
    repository_url: str
    source_path: str
    commit_hash: Optional[str] = None
    license_name: str
    license_notice: str
    imported_at: str


class InterviewQuestionDetail(BaseModel):
    id: str
    slug: str
    domain_id: str
    domain_title: str
    category: str
    topic: str
    title: str
    difficulty: str
    experience_level: Optional[str] = "Mid-Level"
    target_roles: List[str] = Field(default_factory=list)
    markdown_content: str
    raw_content: Optional[str] = None
    estimated_read_time_min: int
    has_code: bool = False
    has_diagram: bool = False
    tags: List[str] = Field(default_factory=list)
    source: SourceAttribution
    educational_diagram: Optional[str] = None
    educational_diagram_alt: Optional[str] = None
    previous_question: Optional[dict] = None  # { "id": str, "title": str, "slug": str }
    next_question: Optional[dict] = None      # { "id": str, "title": str, "slug": str }


class QuestionAIExplainRequest(BaseModel):
    mode: str = "simplify"  # simplify, deep_dive, practice_question, mock_feedback
    user_draft_answer: Optional[str] = None


class QuestionAIExplainResponse(BaseModel):
    question_id: str
    mode: str
    explanation: str
    real_world_scenario: Optional[str] = None
    code_sample: Optional[str] = None
    key_interview_takeaways: List[str] = Field(default_factory=list)
    ai_model_used: str
    is_ai_generated: bool = True
    disclaimer: str = "This explanation was generated by local AI to enhance your preparation and is distinct from the repository source material."


class RepositoryImportRequest(BaseModel):
    domain_id: str
    repository_url: str
    branch: Optional[str] = "main"
    translate_chinese: bool = True
    target_language: str = "en"


class RepositoryImportResponse(BaseModel):
    domain_id: str
    repository_url: str
    status: str
    files_processed: int
    questions_imported: int
    images_resolved: int
    translated_count: int
    content_hash: str
    license_detected: str
    message: str
